name: shopping_app_with_getx
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
#----------[packages]---------
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
  iconsax: 
  carousel_slider: ^5.1.1

  # ---------[state management]
  get: ^4.7.2
  get_storage: ^2.1.1
  readmore: ^3.0.0

  #------[FireBase]-----
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^7.2.0
  
  


 #------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

  #--------[assets]----------
  assets:

    - assets/logo/
    - assets/brands/
    - assets/banners/
    - assets/images/
    - assets/products/
    - assets/icons/categories/
    - assets/animations/
    - assets/icons/payment_methods/


  #--------[fonts]--------
  fonts:
    - family: "Nunito"
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800
       
 